service: sqs-weather-demo

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
       - sqs:SendMessage
       - sqs:ReceiveMessage
       - sqs:DeleteMessage
       - sqs:GetQueueAttributes
      Resource: arn:aws:sqs:us-east-1:463357988722:Weather_request

functions:
  dequeue:
    handler: handler.dequeue
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:463357988722:Weather_request
          batchSize: 1

  enqueue:
    handler: handler.enqueue
    events:
      - http: GET forecast